#!/usr/bin/env bash

MEDIA_DIR='/Users/jdeto/ableton/masters/ep1'
ONEDRIVE="/Users/jdeto/Documents/export/aif/ep1/ep1_masters_$(date '+%m%d%y_%H%M%S')"
RAW_DIR='raw'
OUT_DIR='exp'
IMAGE_FILE='ep1_artwork.png'

PAD_START=500
PAD_END='0.75'

ARTIST='Justin DeKock'
ALBUM='ep1'
YEAR='2026'

# track numbers derived from order of this array
declare -a songs=(
    Zeroth
    RGM
    Surge
    Verso
    Interlude
    Postal
    Transient
    Epilogue
) 

NUM_TRACKS="${#songs[@]}"

declare -A track_nums=()
declare -A genres=()
declare -A comments=()

# derive track numbers from the songs array
for i in "${!songs[@]}"; do
    song="${songs[$i]}"
    echo "idx: $i | song: $song"
    
    track_nums["$song"]=$((i + 1))
    
    genre=''
    comment=''
    case "$song" in 
        Zeroth)
            genre="Indietronica, Indie Pop"
            comment=""
            ;;
        RGM)
            genre="Ambient, Experimental Guitar"
            comment="untitled 001"
            ;;
        Surge)
            genre="Indietronica, Experimental Guitar"
            comment="untitled 005"
            ;;
        Verso)
            genre="Indietronica, Experimental Guitar"
            comment="untitled 004/018"
            ;;
        Interlude)
            genre="Ambient, IDM"
            comment=""
            ;;
        Postal)
            genre="Electronica, Indietronica"
            comment="march"
            ;;
        Transient)
            genre="Electronica, IDM"
            comment="transcend"
            ;;
        Question)
            genre="Electronica, Indietronica"
            comment="untitled question mark / 026"
            ;;
    esac
    genres[$song]="$genre"
    comments[$song]="$comment"

done

for key in "${!track_nums[@]}"; do
    echo "song: $key | track: ${track_nums[$key]}"
done

for key in "${!genres[@]}"; do
    echo "song: $key | genre: ${genres[$key]}"
done

for key in "${!comments[@]}"; do
    echo "song: $key | comment: ${comments[$key]}"
done

mkdir -p "$MEDIA_DIR/$OUT_DIR"

for f in "$MEDIA_DIR/$RAW_DIR"/*.aif; do
    name="$(basename "${f%.aif}")"
    echo "adding "$PAD_START"ms at the beginning and "$PAD_END"s at the end of $name..."
    ffmpeg -y \
        -i "$f" \
        -af "adelay=$PAD_START|$PAD_START,apad=pad_dur=$PAD_END" \
        -c:a pcm_s24be \
        "$MEDIA_DIR/$OUT_DIR/$name".aif


    echo "tagging and attaching $IMAGE_FILE to $name".aif...
    kid3-cli \
        -c "set picture:'$MEDIA_DIR/$IMAGE_FILE' 'Front Cover'" \
        -c "set artist '$ARTIST'" \
        -c "set album '$ALBUM'" \
        -c "set year '$YEAR'" \
        -c "set title '$name'" \
        -c "set genre '${genres[$name]}'" \
        -c "set comment '${comments[$name]}'" \
        -c "set track '${track_nums[$name]}/$NUM_TRACKS'" \
        "$MEDIA_DIR/$OUT_DIR/$name.aif"
done

PLAYLIST="$MEDIA_DIR/$OUT_DIR/ep1.m3u"
{
    echo "#EXTM3U"
    for song in "${songs[@]}"; do
        echo "${song}.aif"
    done
} > "$PLAYLIST"

# copy files to onedrive location
cp -r "$MEDIA_DIR/$OUT_DIR" "$ONEDRIVE"
echo "copied completed files to $ONEDRIVE"
