#!/usr/bin/env bash

MEDIA_DIR='Users/jdeto/ableton/masters/ep1'
RAW_DIR='raw'
OUT_DIR='exp'
IMAGE_FILE='ep1_artwork.png'

PAD_START=500
PAD_END='0.5'

ARTIST='Justin DeKock'
ALBUM='ep1'
YEAR='2026'

# track numbers derived from order of this array
declare -a songs=(
    Zeroth
    RGM
    Surge
    Verso
    Interlude
    Postal
    Transient
    Question
) 

NUM_TRACKS="${#songs[@]}"

declare -A track_nums=()
declare -A genres=()
declare -A comments=()

# derive track numbers from the songs array
for i in "${!songs[@]}"; do
    song="${songs[$i]}"
    echo "idx: $i | song: $song"
    
    track_nums["$song"]=$((i + 1))
    
    genre=''
    comment=''
    case "$song" in 
        Zeroth)
            genre="Indietronica, Indie Pop"
            comment=""
            ;;
        RGM)
            genre="Ambient, Experimental Guitar"
            comment="untitled 001"
            ;;
        Surge)
            genre="Indietronica, Experimental Guitar"
            comment="untitled 005"
            ;;
        Verso)
            genre="Indietronica, Experimental Guitar"
            comment="untitled 004/018"
            ;;
        Interlude)
            genre="Ambient, IDM"
            comment=""
            ;;
        Postal)
            genre="Electronica, Indietronica"
            comment="march"
            ;;
        Transient)
            genre="Electronica, IDM"
            comment="transcend"
            ;;
        Question)
            genre="Electronica, Indietronica"
            comment="untitled question mark / 026"
            ;;
    esac
    ${genres[$name]}="$genre"
    ${comments[$name]}="$comment"

done

for key in "${!track_nums[@]}"; do
    echo "song: $key | track: ${track_nums[$key]}"
done

for key in "${!genres[@]}"; do
    echo "song: $key | genre: ${genres[$key]}"
done

for key in "${!comments[@]}"; do
    echo "song: $key | comment: ${comments[$key]}"
done

mkdir -p "$MEDIA_DIR/$OUT_DIR"

for f in "$MEDIA_DIR/$RAW_DIR/*.aif"; do
    name="${f%.aif}"
    echo "processing $name..."
    ffmpeg -y \
        -i "$f" \
        -af "adelay=$PAD_START|$PAD_START,apad=pad_dur=$PAD_END" \ 
        -metadata artist="$ARTIST" \
        -metadata album="$ALBUM" \
        -metadata year="$YEAR" \
        -metadata title="$name" \
        -metadata genre="${genres[$name]}" \
        -metadata comment="${comments[$name]}" \
        -metadata track="${track_nums[$name]}/$NUM_TRACKS"
done

