#!/usr/bin/env bash

if [ $# -eq 0 ]; then
    echo "Usage: $(basename "$0") <song-name-or-pattern>"
    exit 1
fi

file="$1"
echo "Loudness (LUFS): $(basename "$file")"
ffmpeg -i "$file" -af ebur128 -f null - 2>&1 | sed -n '/Summary/,$p'
