#!/usr/bin/env bash

IN=raw
OUT=padded
ARTIST="Justin DeKock"
ALBUM="ep1"
YR="2026"

PSTART=500
PEND="0.5"

mkdir -p $OUT

cd $IN

for f in *.aif; do
    echo "padding $IN/$f ..."
    name="${f%.aif}"
    ffmpeg -y -i "$f" -af "adelay=$PSTART|$PSTART,apad=pad_dur=$PEND" \
        -metadata title="$name" -metadata artist="$ARTIST" -metadata album="$ALBUM" -metadata year="$YR"\
        "../$OUT/$f"
done

echo "complete"
